// ============================================================
//  Shared constants — the single source of truth for enums and
//  defaults used across the backend, website, and admin. Safe to
//  import from both server and client code (no secrets here).
// ============================================================

/** License lifecycle states. Only ACTIVE is usable by the extension. */
export const LICENSE_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
  BLOCKED: "BLOCKED",
  SUSPENDED: "SUSPENDED",
} as const;
export type LicenseStatus = (typeof LICENSE_STATUS)[keyof typeof LICENSE_STATUS];

/** The states in which a signed license lets the extension run. */
export const USABLE_LICENSE_STATUSES: LicenseStatus[] = [LICENSE_STATUS.ACTIVE];

/** Per-device activation states. */
export const ACTIVATION_STATUS = {
  ACTIVE: "ACTIVE",
  DEACTIVATED: "DEACTIVATED",
} as const;
export type ActivationStatus =
  (typeof ACTIVATION_STATUS)[keyof typeof ACTIVATION_STATUS];

/** Manual bKash purchase request states. */
export const PURCHASE_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
} as const;
export type PurchaseStatus =
  (typeof PURCHASE_STATUS)[keyof typeof PURCHASE_STATUS];

/** Subscription record states. */
export const SUBSCRIPTION_STATUS = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
} as const;
export type SubscriptionStatus =
  (typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS];

/** Audit log action types (see Phase 55). */
export const AUDIT_ACTION = {
  LICENSE_CREATED: "LICENSE_CREATED",
  LICENSE_ACTIVATED: "LICENSE_ACTIVATED",
  LICENSE_REVOKED: "LICENSE_REVOKED",
  LICENSE_BLOCKED: "LICENSE_BLOCKED",
  LICENSE_SUSPENDED: "LICENSE_SUSPENDED",
  LICENSE_REACTIVATED: "LICENSE_REACTIVATED",
  LICENSE_EXTENDED: "LICENSE_EXTENDED",
  LICENSE_DEVICE_LIMIT_CHANGED: "LICENSE_DEVICE_LIMIT_CHANGED",
  LICENSE_KEY_REVEALED: "LICENSE_KEY_REVEALED",
  DEVICE_ACTIVATED: "DEVICE_ACTIVATED",
  DEVICE_DEACTIVATED: "DEVICE_DEACTIVATED",
  DEVICE_RESET: "DEVICE_RESET",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_EXTENDED: "SUBSCRIPTION_EXTENDED",
  PLAN_CREATED: "PLAN_CREATED",
  PLAN_UPDATED: "PLAN_UPDATED",
  ADMIN_CREATED: "ADMIN_CREATED",
  ADMIN_LOGIN: "ADMIN_LOGIN",
} as const;
export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

/** Current signed-license payload version. Bump on breaking payload changes. */
export const LICENSE_PAYLOAD_VERSION = 1 as const;

/** License key format: 4 groups of 4 Crockford-base32 chars → XXXX-XXXX-XXXX-XXXX */
export const LICENSE_KEY_REGEX = /^[0-9A-HJ-NP-Z]{4}-[0-9A-HJ-NP-Z]{4}-[0-9A-HJ-NP-Z]{4}-[0-9A-HJ-NP-Z]{4}$/;

/** Installation id: a UUID v4 generated by the extension (no fingerprinting). */
export const INSTALLATION_ID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Default seed plans (created by `npm run setup:db` if none exist). BDT. */
export const DEFAULT_PLANS = [
  { name: "1 PC", deviceLimit: 1, price: 1500, durationDays: 30, active: true },
  { name: "3 PC", deviceLimit: 3, price: 3500, durationDays: 30, active: true },
  { name: "5 PC", deviceLimit: 5, price: 5000, durationDays: 30, active: true },
] as const;

export const CURRENCY = "BDT" as const;
